version: '3'
services:
  postgres:
    build: './postgres'
    ports:
      - '5432:5432'
    environment:
      - "PG_DB_USER=khoa"
      - "PG_DB_PASSWORD=khoa"
      - "PG_DB_DATABASE=sickfits_dev"
      - "POSTGRES_PASSWORD=password"
  prisma:
    image: prismagraphql/prisma:1.34
    links:
      - postgres
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            database: sickfits_dev
            schema: public
            user: postgres
            password: password
            rawAccess: true
            port: '5432'
            migrations: true
